### ISSUE TITLE
Scrollbar for Maps needed

### ISSUE THREAD

**Issue by LaChicaZ** [emre1702/TDS-V-Public#125]
There are to many Maps on the Menu and you cant scroll down
![b734c9b8ba4f4a5fd79539bed68becee 1](https://user-images.githubusercontent.com/20823131/93361079-b799dc80-f844-11ea-9287-3d67179c7ee1.jpg)

**Comment by emre1702** [comment]
2 bugs (this + the blackish color) in one ... nice
Thank you very much, fixed.
