### ISSUE TITLE
[BUG] Schreibfehler auf Map "Lagerhalle-LS"

### ISSUE THREAD

**Issue by n0pe97** [emre1702/TDS-V-Public#126]
**Beschreibe den Bug**
Schreibfehler auf der Map Lagerhalle-LS
Fehler: Verhinde die Bomben-Explosion oder töte alle Gegner!
**Erwartetes Verhalten**
Verhindere die Bomben-Explosion oder töte alle Gegner!

**Screenshots / Logs**
https://prnt.sc/uoij5q

**Deine User-ID**
22

**Comment by emre1702** [comment]
Gefixt, danke.
