### ISSUE TITLE
[SUGGESTION] Which weapons for Arena?

### ISSUE THREAD

**Issue by emre1702** [emre1702/TDS-V-Public#133]
Which weapons should we use for Arena?

Possible weapons are:
Sniperrifle, Fireextinguisher, Compactlauncher, Snowball, Vintagepistol, Combatpdw, Heavysniper_mk2, Heavysniper, Autoshotgun, Microsmg, Wrench, Pistol, Pumpshotgun, Appistol, Ball, Molotov, CeramicPistol, Smg, Stickybomb, Petrolcan, Stungun, Stone_hatchet, Assaultrifle_mk2, Heavyshotgun, Minigun, Golfclub, Raycarbine, Flaregun, Flare, Grenadelauncher_smoke, Hammer, Pumpshotgun_mk2, Combatpistol, Gusenberg, Compactrifle, Hominglauncher, Nightstick, Marksmanrifle_mk2, Railgun, Sawnoffshotgun, Smg_mk2, Bullpuprifle, Firework, Combatmg, Carbinerifle, Crowbar, Bullpuprifle_mk2, Snspistol_mk2, Flashlight, Proximine, NavyRevolver, Dagger, Grenade, Poolcue, Bat, Specialcarbine_mk2, Doubleaction, Pistol50, Knife, Mg, Bullpupshotgun, Bzgas, Unarmed, Grenadelauncher, Musket, Advancedrifle, Raypistol, Rpg, Rayminigun, Pipebomb, HazardCan, Minismg, Snspistol, Pistol_mk2, Assaultrifle, Specialcarbine, Revolver, Marksmanrifle, Revolver_mk2, Battleaxe, Heavypistol, Knuckle, Machinepistol, Combatmg_mk2, Marksmanpistol, Machete, Switchblade, Assaultshotgun, Dbshotgun, Assaultsmg, Hatchet, Bottle, Carbinerifle_mk2, Parachute, Smokegrenade

See:
https://wiki.rage.mp/index.php?title=Weapons

**Comment by LaChicaZ** [comment]
Fist
weapon_pistol50
weapon_revolver
weapon_smg
weapon_combatpdw
weapon_musket
weapon_sawnoffshotgun
weapon_assaultrifle
