### ISSUE TITLE
[SUGGESTION] Welchen Map-Limit-Typen für Arena nutzen?

### ISSUE THREAD

**Issue by emre1702** [emre1702/TDS-V-Public#81]
Es gibt diese drei Map-Limiten-Typen, die wir für die Arena nutzen können:

1. Teleport nach Zeit:
Man wird nach Ablauf der Zeit (wohl 10 Sekunden) zur letzten Position innerhalb der Map teleportiert.

2. Kill nach Zeit:
Man stirbt nach Ablauf der Zeit (wohl 10 Sekunden).

3. Block:
Man kommt nicht raus, wird bei Austreten aus der Map direkt wieder zurück teleportiert.

Zur Zeit wird "Kill nach Zeit" benutzt, da die Spieler dadurch mehr Taktik Möglichkeiten bekommen und auch risikoreiche Spielzüge tätigen können.
Block wurde bei TDS-SA benutzt, jedoch hat es gewisse Nachteile:
1. Unperformanter (10-20x)
2. Kann im Kampf nervig sein, wenn man ausversehen die Map verlässt

Was würdet ihr vorschlagen?

**Comment by LaChicaZ** [comment]
Lass es so wie es ist, also 2.
