### ISSUE TITLE
[SUGGESTION] Ingame Blips erstellen im Map Creator

### ISSUE THREAD

**Issue by Peanutabi** [emre1702/TDS-V-Public#83]
hi,

ihr kennt bestimmt das Problem, ihr erstellt gerade eine Map, stellt gerade die Team Spawns ein und versucht eine möglichst schöne reihe hin zu bekommen. Was jedoch recht schwierig ist, weil man nicht genau weiß wo der letzte Team Spawn war. 

Also schlage ich vor bei den Team Spawns einen Marker oder Blip zu erstellen wenn man Team Spawns hin zu fügt.

Dazu wäre noch ein Icon auf dem GPS ehrenhaft wenn man Map limits einstellt. Damin man die Map limits besser machen kann.

regards,
PEANUT

**Comment by emre1702** [comment]
Erledigt
